image: node:14.15.0-alpine3.12

before_script:
  - npm install -g @angular/cli
  - npm install

stages:
  - build

cache:
  paths:
    - node_modules

build:
  stage: build
  script:
    - ng build --prod
